name: Build and Deploy React App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Navigate to the correct project directory
      - name: Change to React project directory
        working-directory: vscode/showcase/react-nodejs/book-selling-app/front-end
        run: echo "Now in React project directory"

      # 4. Install dependencies
      - name: Install dependencies
        working-directory: vscode/showcase/react-nodejs/book-selling-app/front-end
        run: npm install

      # 5. Build the React app
      - name: Build the project
        working-directory: vscode/showcase/react-nodejs/book-selling-app/front-end
        run: npm run build

      # 6. Clone the GitHub Pages repository (your showcase repo)
      - name: Clone showcase repository
        run: |
          git clone https://github.com/cubes786/cubes786.github.io.git ../cubes786.github.io

      # 7. Copy the build output to the subfolder in the showcase repo
      - name: Copy build files to shopping-portal folder
        run: |
          rm -rf ../cubes786.github.io/showcase/shopping-portal
          mkdir -p ../cubes786.github.io/showcase/shopping-portal
          cp -R vscode/showcase/react-nodejs/book-selling-app/front-end/build/* ../cubes786.github.io/showcase/shopping-portal/

      # 8. Commit and push the changes to the showcase repo
      - name: Deploy changes to GitHub Pages
        working-directory: ../cubes786.github.io
        env:
          GITHUB_PAT: ${{ secrets.DEPLOY_PAT }}  # Use Personal Access Token
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://cubes786:${{ secrets.DEPLOY_PAT }}@github.com/cubes786/cubes786.github.io.git
          git add showcase/shopping-portal
          git commit -m "Deploy shopping portal update from commit ${{ github.sha }}" || echo "No changes to commit"
          git push origin main
